### ISSUE TITLE
'My Favorites' with custom url does not work

### ISSUE THREAD

**Issue by vladogol** [rols1/TuneIn2017#1]
Thanks for the awesome plugin, but I have faced some issue.
I have account in TuneIn. Using TuneIn for iOS I have added custom station (by URL) to My Favorites list (this one: http://live.radioec.com.ua:8000/kiev) and I can play it in TuneIn iOS app.
I have installed TuneIn2017 channel in Plex, entered my TuneIn login and found added custom URL in the list, but when I hit 'play' nothing happened - I only was able to see "loading" animation. 
I have checked logs and looks like it got stuck on this: 
`2017-10-07 23:05:20,383 (-c1c24c0) : INFO (__init__:238) - Rubriken: http://live.radioec.com.ua:8000/kiev`
More logs attached.

Hope to have this issue fixed to be able to listen custom streams using Plex with TuneIn
Thanks.
[tunein.log](https://github.com/rols1/TuneIn2017/files/1366409/tunein.log)

**Comment by rols1** [comment]
Hi,
tomorrow I will create an account in TuneIn and will look how the CustomUrl is organized. You are the first who asks for it - but as I can read on the website, it seems an important feature.  
I think it should be solved - if not via TuneIn-API, than via an additonal plugin-function (input-field in preferences, a local file edited by hand, or somewhat else).
I will give feedback...
/R

**Comment by rols1** [comment]
solved - please show Forum: https://forums.plex.tv/discussion/comment/1533162/#Comment_1533162
btw: if you want to translate the plugin in your native language (only 20 terms), please take a look here: https://poeditor.com/join/project/SKrMQklJVu
/R
